title: Ezekiel Seun Oladimeji
logo: Newimage.jpg
description: I am a Data Analyst with over two years experience in data analysis, adept with statistical and data analytics tools such as Python, Machine Learning, Excel, SQL, and Power BI. Specializing in leveraging data insights for business decisions, I am also proficient in Microsoft Office and data manipulation, which enhances my ability to provide valuable analytical solutions.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
